### ISSUE TITLE
Not able to add AAPM Restrictions from AEM Permission console.

### ISSUE THREAD

**Issue by maroofkhanvaltech** [valtech/aem-advanced-permissions-manager#7]
Add a permission restriction from `AEM Security | Permissions` console.

On adding restriction like `hasPropertyValues: allow#string$cq:tags==properties:orientation/portrait` and saving it from the UI is not adding the appropriate restriction in the `rep:policy` node.

It seems for the symbol `=` the property is not storing in rep:policy, might be due to some logic present in the backend code responsible for using these values when saving it from the permission console UI.

**Comment by gruberrolandvaltech** [comment]
A solution could be to use EQUALS, LESS, GREATER
