### ISSUE TITLE
Check if allow/deny is needed as part of the property

### ISSUE THREAD

**Issue by gruberrolandvaltech** [valtech/aem-advanced-permissions-manager#9]
See https://gist.github.com/mchrominski/8ad8975d916ac24dca25 where such data is not required.
The logic for allow/deny also seems to be not consistent.

**Comment by vivekmalviya0104** [comment]
Hi @gruberrolandvaltech ,
I checked the above link and it is related to just hiding any property on which whenever the restriction(rep:hideProperty) is set. However, in our case, we are using 2 options for the property values; if prefix with  _allow_ we show the assets having the a certain property value and hide the assets if prefix  with _deny_ on same property value
In our case, we do need Allow/Deny as part of rep:hasPropertyValues.
